FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN curl -sSL https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64 -o /usr/local/bin/shfmt \
    && sudo chmod 777 /usr/local/bin/shfmt
